include $(CONTIKI)/platform/quark-d2000-devboard/Makefile.bsp-quark-d2000-devboard
include $(CONTIKI)/platform/qmsi-common/Makefile.qmsi-common

CONTIKI_TARGET_DIRS += .
CONTIKIFILES += contiki-main.c
CONTIKI_TARGET_MAIN = ${addprefix $(OBJECTDIR)/,contiki-main.o}

LDFLAGS += -T $(QMSI_PATH)/soc/quark_d2000/quark_d2000.ld
