include $(CONTIKI)/platform/qmsi-common/Makefile-bsp-qmsi-common

LIBQMSI_INCLUDE_DIR = $(QMSI_PATH)/build/release/quark_d2000/libqmsi/include
LIBQMSI_LIB_DIR = $(QMSI_PATH)/build/release/quark_d2000/libqmsi/lib

FIRMWARE = $(QMSI_PATH)/build/release/quark_d2000/rom/quark_d2000_rom.bin
