include $(CONTIKI)/platform/qmsi-common/Makefile.customrules-qmsi-common

.PHONY: flash flash-firmware debug

flash: $(CONTIKI_PROJECT)
	$(BSP)/flasher/flasher.sh quark_d2000 --flash $(shell pwd)/$(CONTIKI_PROJECT).$(TARGET)

flash-firmware: $(FIRMWARE)
	$(BSP)/flasher/flasher.sh quark_d2000 --rom $(shell pwd)/$<

debug:
	$(BSP)/flasher/flasher.sh quark_d2000 --debug $(shell pwd)/$(CONTIKI_PROJECT).$(TARGET)
