include $(CONTIKI)/platform/qmsi-common/Makefile.customrules-qmsi-common

.PHONY: flash flash-firmware debug

flash: $(CONTIKI_PROJECT)
	$(BSP)/flasher/flasher.sh quark_se --flash $(shell pwd)/$(ELF)

flash-firmware: $(FIRMWARE)
	$(BSP)/flasher/flasher.sh quark_se --rom $(shell pwd)/$<

debug: $(ELF)
	$(BSP)/flasher/flasher.sh quark_se --debug $(shell pwd)/$<
